### ISSUE TITLE
Need better way to stop unregistered users from entering dashboard and admin pages

### ISSUE THREAD

**Issue by Turtle84375** [Turtle84375/turtle84375.me#2]
^

**Comment by lankybox02** [comment]
It all comes down to how your authentication system works.
I'm going to try to do a small prototype for a simple dashboard system,. i'll post updates here

**Comment by Turtle84375** [comment]
I've been working on the auth system for the past 2 hours, and I have a pretty solid login/registration system (https://github.com/Turtle84375/auth.turtle84375.me) but I need a better way to enforce it.
